dcConsData = [
	{name:"소닉링없찐.gif", keywords:["링없찐"], tags:["소닉"]},
	{name:"소닉결혼반지.png", keywords:["결혼반지"],	tags:["소닉"]},
	{name:"눈물소닉.png", keywords:["눈물소닉", "소닉눈물"],	tags:["소닉"]},
	{name:"눈물에이미.png", keywords:["눈물에이미", "에이미눈물"],	tags:["소닉"]},
	{name:"눈물너클즈.png", keywords:["눈물너클즈", "너클즈눈물"],	tags:["소닉"]},
	{name:"눈물테일즈.png", keywords:["눈물테일즈", "테일즈눈물"],	tags:["소닉"]},
	{name:"소닉붐.png", keywords:["소닉붐"],	tags:["소닉"]},
	{name:"싸닉.png", keywords:["싸닉"],	tags:["소닉"]},
	{name:"싸닉매니아.png", keywords:["싸닉매니아"],	tags:["소닉"]},
	{name:"싸도우.png", keywords:["싸도우"],	tags:["소닉"]},
	{name:"나클즈.png", keywords:["나클즈"],	tags:["소닉"]},
	{name:"따일즈.png", keywords:["따일즈"],	tags:["소닉"]},
	
	{name:"꿀벌1.png", keywords:["꿀벌기쁨"],	tags:["꿀벌"]},
	{name:"꿀벌2.png", keywords:["꿀벌눈물"],	tags:["꿀벌"]},
	{name:"꿀벌3.png", keywords:["꿀벌화남"],	tags:["꿀벌"]},
	{name:"꿀벌댄스.gif", keywords:["꿀벌댄스"],	tags:["꿀벌"]},
	{name:"모짜놀람.png", keywords:["모짜놀람"],	tags:["미분류"]},
	{name:"모짜회전.gif", keywords:["모짜회전"],	tags:["미분류"]},
	
	{name:"달껄룩.png", keywords:["달껄룩"],	tags:["레인월드"]},
	{name:"샌즈껄룩.png", keywords:["샌즈껄룩"],	tags:["레인월드"]},
	
	{name:"대기.gif", keywords:["대기"],	tags:["미분류"]},

	{name:"군침.gif", keywords:["군침"],	tags:["미분류"]},
	{name:"티배깅마리사.gif", keywords:["티배깅마리사"],	tags:["미분류"]},

	{name:"댄스로이.gif", keywords:["댄스로이"],	tags:["미분류"]},
	{name:"불편.png", keywords:["불편"],	tags:["미분류"]},
	{name:"편안.png", keywords:["편안"],	tags:["미분류"]},
	{name:"손닦.jpg", keywords:["손닦", "손씻기"],	tags:["미분류"]},
	{name:"손닦2.jpg", keywords:["손닦2", "손씻기2"],	tags:["미분류"]},
	{name:"손도깔끔.png", keywords:["손도깔끔"],	tags:["미분류"]},
	{name:"치킨가이.gif", keywords:["치킨가이", "치킨"],	tags:["미분류"]},
	{name:"함정.png", keywords:["함정"],	tags:["미분류"]},
	{name:"관짝댄스.gif", keywords:["관짝댄스", "관짝"],	tags:["미분류"]},
	{name:"관짝댄스2.gif", keywords:["관짝댄스2", "관짝2"],	tags:["미분류"]},
	{name:"관짝준비.gif", keywords:["관짝준비"],	tags:["미분류"]},
	{name:"광클.gif", keywords:["광클"],	tags:["미분류"]},
	{name:"게이븐.png", keywords:["게이븐"],	tags:["미분류"]},
	{name:"브레인.jpg", keywords:["브레인"],	tags:["미분류"]},
	{name:"브레인2.jpg", keywords:["브레인2"],	tags:["미분류"]},
	{name:"브레인3.jpg", keywords:["브레인3"],	tags:["미분류"]},
	{name:"브레인4.jpg", keywords:["브레인4"],	tags:["미분류"]},
	{name:"콜라.png", keywords:["콜라"],	tags:["미분류"]},
	{name:"펩시.jpg", keywords:["펩시"],	tags:["미분류"]},
	{name:"나루토런.png", keywords:["나루토런"],	tags:["미분류"]},
	{name:"딱대.png", keywords:["딱대"],	tags:["미분류"]},
	{name:"에이블톤라이브.png", keywords:["에이블톤"],	tags:["미분류"]},
	
	{name:"둘리ㅋㅋ.png", keywords:["둘리ㅋㅋ"],	tags:["둘리"]},
	{name:"무슨냄새.png", keywords:["무슨냄새"],	tags:["둘리"]},
	{name:"깐따삐야.png", keywords:["깐따삐야"],	tags:["둘리"]},
	{name:"선넘.png", keywords:["선넘"],	tags:["둘리"]},
	{name:"성능확실.png", keywords:["성능확실"],	tags:["둘리"]},
	{name:"어서오고.png", keywords:["어서오고"],	tags:["둘리"]},
	{name:"좋지.png", keywords:["좋지"],	tags:["둘리"]},
	{name:"철썩.png", keywords:["철썩"],	tags:["둘리"]},
	
	{name:"라이젠.png", keywords:["라이젠"],	tags:["컴퓨터"]},
	{name:"인텔.png", keywords:["인텔"],	tags:["컴퓨터"]},
	{name:"암드.png", keywords:["암드"],	tags:["컴퓨터"]},
	{name:"리사수.png", keywords:["리사수"],	tags:["컴퓨터"]},
	{name:"힙사수.gif", keywords:["힙사수"],	tags:["컴퓨터"]},
	{name:"프로그래밍.gif", keywords:["프로그래밍"],	tags:["컴퓨터"]},
	{name:"읒증.png", keywords:["읒증"],	tags:["컴퓨터"]},
	
	{name:"볼트공중.png", keywords:["볼트공중"],	tags:["볼트"]},
	{name:"볼트따봉.png", keywords:["볼트따봉"],	tags:["볼트"]},
	
	{name:"심영박수.gif", keywords:["심영박수"],	tags:["야인시대"]},
	{name:"심영박수2.gif", keywords:["심영박수2"],	tags:["야인시대"]},
	{name:"상하이조.gif", keywords:["상하이조"],	tags:["야인시대"]},
	{name:"폭발.gif", keywords:["폭발"],	tags:["야인시대"]},

	{name:"흠.png", keywords:["흠"],	tags:["흠"]},
	{name:"왜곡흠.gif", keywords:["왜곡흠"],	tags:["흠"]},
	{name:"발퀄흠.png", keywords:["발퀄흠"],	tags:["흠"]},
	{name:"혼란흠.gif", keywords:["혼란흠"],	tags:["흠"]},
	{name:"흠흠흠.png", keywords:["흠흠흠"],	tags:["흠"]},
	{name:"회전흠.gif", keywords:["회전흠"],	tags:["흠"]},
	{name:"회전흠2.gif", keywords:["회전흠2"],	tags:["흠"]},
	{name:"회전흠3.gif", keywords:["회전흠3"],	tags:["흠"]},

	{name:"페페흐음.png", keywords:["페페흐음"],	tags:["페페"]},
	{name:"화난페페.png", keywords:["화난페페, 페페분노"],	tags:["페페"]},
	{name:"앵그리페페2.png", keywords:["화난페페2, 페페분노2, 앵그리페페2"],	tags:["페페"]},
	{name:"페페우산.gif", keywords:["페페우산"],	tags:["페페"]},
	
	{name:"제리인사.gif", keywords:["제리인사"],	tags:["톰과제리"]},
	{name:"제리감사.gif", keywords:["제리감사"],	tags:["톰과제리"]},
	{name:"제리폭소.gif", keywords:["제리폭소"],	tags:["톰과제리"]},
	{name:"톰감사.gif", keywords:["톰감사"],	tags:["톰과제리"]},
	{name:"톰박수.gif", keywords:["톰박수"],	tags:["톰과제리"]},

	{name:"혼란앵무.gif", keywords:["혼란앵무"],	tags:["혼란앵무"]},
	{name:"더블앵무.gif", keywords:["더블앵무"],	tags:["혼란앵무"]},
	
	{name:"겉바속촉.gif", keywords:["겉바속촉", "가로쉬"],	tags:["와우", "헬스크림"]},
	
	{name:"딸기.png", keywords:["딸기"], tags:["미분류"]},
	{name:"나씨씨트로피.gif", keywords:["나씨씨트로피", "트로피"],	tags:["나씨씨"]}
];
